/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.patrick.todolist.view;

import br.com.patrick.todolist.controller.MetodosTarefaController;
import br.com.patrick.todolist.model.MetodosTarefaModel;
import br.com.patrick.todolist.model.TarefasModel;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author Patrick
 */
public class CustomPanel extends javax.swing.JPanel {

  private MetodosTarefaController metodoscontroller;
  private MetodosTarefaModel metodosTarefaModel;
  private TarefasModel tarefa;
  private int taskId; // Adiciona uma variável para armazenar o id da tarefa
  private MenuView menuView;


    
    


   public CustomPanel(int taskId, String titulo, String descricao) {
        initComponents();
        this.taskId = taskId; // Armazena o id da tarefa
        upperLabel.setText(titulo);
        lowerLabel.setText(descricao);
         metodosTarefaModel = new MetodosTarefaModel(); // Inicializa o modelo
        metodoscontroller = new MetodosTarefaController(metodosTarefaModel); // Instancia o controlador
    }
   
   public CustomPanel(MenuView menuView, int taskId, String titulo, String descricao) {
    initComponents();
    this.menuView = menuView; // Armazena uma referência ao MenuView
    this.taskId = taskId; // Armazena o id da tarefa
    upperLabel.setText(titulo);
    lowerLabel.setText(descricao);
    metodosTarefaModel = new MetodosTarefaModel(); // Inicializa o modelo
    metodoscontroller = new MetodosTarefaController(metodosTarefaModel); // Instancia o controlador
}
   
    public void pegarDados() {
    List<TarefasModel> tarefas = metodoscontroller.obterTodasTarefas();
    for (TarefasModel tarefa : tarefas) {
        int id = tarefa.getId();
        String titulo = tarefa.getTitulo();
        String descricao = tarefa.getDescricao();

        // Cria um novo CustomPanel com os parâmetros título, descrição e id
        CustomPanel customPanel = new CustomPanel(id, titulo, descricao);

        // Adiciona o customPanel ao jPanel2
    
    }
   }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperLabel = new javax.swing.JLabel();
        lowerLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRemoverTarefa = new javax.swing.JButton();
        btnEditarTarefa = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));

        upperLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        upperLabel.setForeground(new java.awt.Color(255, 255, 255));
        upperLabel.setText("jLabel1");

        lowerLabel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lowerLabel.setForeground(new java.awt.Color(255, 255, 255));
        lowerLabel.setText("jLabel1");
        lowerLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jSeparator1.setBackground(new java.awt.Color(40, 40, 40));
        jSeparator1.setForeground(new java.awt.Color(40, 40, 40));

        btnRemoverTarefa.setBackground(new java.awt.Color(33, 33, 33));
        btnRemoverTarefa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Patrick\\Downloads\\Ellipse 15.png")); // NOI18N
        btnRemoverTarefa.setBorder(null);
        btnRemoverTarefa.setBorderPainted(false);
        btnRemoverTarefa.setContentAreaFilled(false);
        btnRemoverTarefa.setFocusPainted(false);
        btnRemoverTarefa.setFocusable(false);
        btnRemoverTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverTarefaActionPerformed(evt);
            }
        });

        btnEditarTarefa.setBackground(new java.awt.Color(33, 33, 33));
        btnEditarTarefa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Patrick\\Desktop\\Design sem nome (1).png")); // NOI18N
        btnEditarTarefa.setBorder(null);
        btnEditarTarefa.setBorderPainted(false);
        btnEditarTarefa.setContentAreaFilled(false);
        btnEditarTarefa.setFocusPainted(false);
        btnEditarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnRemoverTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lowerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(upperLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarTarefa)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(upperLabel)
                    .addComponent(btnRemoverTarefa)
                    .addComponent(btnEditarTarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverTarefaActionPerformed
        
 
    metodoscontroller.removerTarefa(taskId);
    menuView.removerCustomPanel(this); // Remover o CustomPanel do MenuView
    }//GEN-LAST:event_btnRemoverTarefaActionPerformed

    private void btnEditarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTarefaActionPerformed
            System.out.println(taskId);
    EditarTarefa editarTarefa = new EditarTarefa();
    editarTarefa.setTaskId(taskId); // Define o taskId na instância de EditarTarefa
    editarTarefa.setVisible(true);
    menuView.dispose();

      
          
        
    }//GEN-LAST:event_btnEditarTarefaActionPerformed

    public int getTaskId() {
        return taskId;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarTarefa;
    private javax.swing.JButton btnRemoverTarefa;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lowerLabel;
    private javax.swing.JLabel upperLabel;
    // End of variables declaration//GEN-END:variables
}
