/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.patrick.todolist.view;

import br.com.patrick.todolist.controller.MetodosTarefaController;
import br.com.patrick.todolist.model.MetodosTarefaModel;
import br.com.patrick.todolist.model.TarefasModel;
import java.util.List;

/**
 *
 * @author Patrick
 */
public class EditarTarefa extends javax.swing.JFrame {

  private MetodosTarefaController metodoscontroller;
  private MetodosTarefaModel metodosTarefaModel;
  private TarefasModel tarefa;
  private int taskId;
private MenuView menuView;

  private int idTaskEditada; // Adiciona uma variável para armazenar o id da tarefa
  
  
    public EditarTarefa() {
        initComponents();
       
        metodosTarefaModel = new MetodosTarefaModel(); // Inicializa o modelo
        metodoscontroller = new MetodosTarefaController(metodosTarefaModel); // Instancia o controlador
    }
   
   
    public void pegarDados() {
    List<TarefasModel> tarefas = metodoscontroller.obterTodasTarefas();
    for (TarefasModel tarefa : tarefas) {
        int id = tarefa.getId();
        String titulo = tarefa.getTitulo();
        String descricao = tarefa.getDescricao();

  
    
    }

    }
    
       public void setTaskId(int taskId) {
        this.taskId = taskId;
    }

     



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEditarTitulo = new javax.swing.JTextField();
        txtEditarDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDesistir = new javax.swing.JButton();
        btnEditarTarefaNova1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        txtEditarTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtEditarDescricao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Titulo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição");

        btnDesistir.setBackground(new java.awt.Color(33, 33, 33));
        btnDesistir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnDesistir.setForeground(new java.awt.Color(33, 33, 33));
        btnDesistir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Patrick\\Desktop\\Design sem nome (6).png")); // NOI18N
        btnDesistir.setBorder(null);
        btnDesistir.setBorderPainted(false);
        btnDesistir.setContentAreaFilled(false);
        btnDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesistirActionPerformed(evt);
            }
        });

        btnEditarTarefaNova1.setBackground(new java.awt.Color(33, 33, 33));
        btnEditarTarefaNova1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnEditarTarefaNova1.setForeground(new java.awt.Color(204, 204, 204));
        btnEditarTarefaNova1.setText("Editar");
        btnEditarTarefaNova1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditarTarefaNova1.setContentAreaFilled(false);
        btnEditarTarefaNova1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTarefaNova1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtEditarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditarTarefaNova1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtEditarDescricao))))
                .addGap(54, 54, 54)
                .addComponent(btnDesistir)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnDesistir)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnEditarTarefaNova1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesistirActionPerformed
        
              this.dispose();
            MenuView novaMenuView = new MenuView();
                novaMenuView.setVisible(true);

    }//GEN-LAST:event_btnDesistirActionPerformed

    private void btnEditarTarefaNova1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTarefaNova1ActionPerformed
        
                System.out.println(taskId);
        
        String novoTitulo = txtEditarTitulo.getText();
        String novaDescricao = txtEditarDescricao.getText();
        int id = taskId;
        
           System.out.println(id);
           System.out.println(novoTitulo);
           System.out.println(novaDescricao);
           
 // Se ambos título e descrição estiverem vazios, não faz nada
    if (novoTitulo.isEmpty() && novaDescricao.isEmpty()) {
       
        return;
        
    }
    
    // Verifica se o título está vazio e a descrição não
    if (novoTitulo.isEmpty() && !novaDescricao.isEmpty()) {
        // Se o título estiver vazio e a descrição não, chama a função para editar a descrição
        metodoscontroller.editarDescricaoTarefa(taskId, novaDescricao);
    } 
    // Verifica se o título não está vazio e a descrição está vazia
    else if (!novoTitulo.isEmpty() && novaDescricao.isEmpty()) {
        // Se o título não estiver vazio e a descrição estiver vazia, chama a função para editar o título
        metodoscontroller.editarTituloTarefa(taskId, novoTitulo);
    } 
    // Se nenhum dos casos acima ocorrer, significa que ambos título e descrição estão preenchidos
    else {
        // Nesse caso, chama a função para editar ambos
        metodoscontroller.editarTarefa(taskId, novoTitulo, novaDescricao);
    }
           
       
               this.dispose();
            MenuView novaMenuView = new MenuView();
                novaMenuView.setVisible(true);
        
        
    }//GEN-LAST:event_btnEditarTarefaNova1ActionPerformed

    public void voltar() {
           this.dispose();
            MenuView novaMenuView = new MenuView();
                novaMenuView.setVisible(true);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
    EditarTarefa editarTarefa = new EditarTarefa();
            // Torna a instância visível
            editarTarefa.setVisible(true);
            
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesistir;
    private javax.swing.JButton btnEditarTarefaNova1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEditarDescricao;
    private javax.swing.JTextField txtEditarTitulo;
    // End of variables declaration//GEN-END:variables
}
